<template>
	<view class="login-page">
		<view class="login-visual"><view class="brand">🐾 宠爱有家</view><view class="visual-copy"><text class="visual-title">用心陪伴，宠爱一生</text><text class="visual-sub">一站式宠物综合服务平台</text><view class="trust"><text>♢ 安全可靠</text><text>♡ 专业贴心</text><text>◎ 品质服务</text></view></view><view class="animals">🐶🐱</view></view>
		<view class="login-panel">
			<view class="mobile-brand">🐾 宠爱有家</view>
			<view class="tabs"><view :class="{active:mode==='password'}" @click="mode='password'">密码登录</view><view :class="{active:mode==='register'}" @click="mode='register'">注册账号</view></view>
			<view class="field"><text>♙</text><input v-model.trim="account" type="text" placeholder="请输入手机号/账号"/></view>
			<view v-if="mode==='register'" class="field"><text>♢</text><input v-model="smsCode" maxlength="6" placeholder="请输入验证码"/><text class="code-button" @click="sendCode">{{countdown?`${countdown}s`:'获取验证码'}}</text></view>
			<view class="field"><text>⌁</text><input v-model="credential" password :placeholder="mode==='password'?'请输入密码':'设置至少 8 位密码'"/></view>
			<view v-if="mode==='register'" class="field"><text>♡</text><input v-model.trim="nickname" maxlength="64" placeholder="昵称（选填）"/></view>
			<view class="agreement" @click="agreed=!agreed"><text class="check" :class="{checked:agreed}">{{agreed?'✓':''}}</text><text>我已阅读并同意《用户协议》和《隐私政策》</text></view>
			<button class="primary-button" :loading="submitting" @click="submit">{{mode==='password'?'立即登录':'完成注册'}}</button>
			<view class="login-extra"><text @click="mode=mode==='password'?'register':'password'">{{mode==='password'?'注册账号':'返回登录'}}</text><text @click="guest">游客浏览</text></view>
			<view class="security-tip">登录即代表你同意平台仅在提供服务所需范围内处理个人信息</view>
		</view>
	</view>
</template>
<script>
import{authApi}from'../../api';import{setTokens}from'../../api/request'
export default{data(){return{mode:'password',account:'',credential:'',smsCode:'',nickname:'',agreed:false,submitting:false,countdown:0,timer:null}},onUnload(){if(this.timer)clearInterval(this.timer)},methods:{async sendCode(){if(this.countdown)return;if(!/^1[3-9]\d{9}$/.test(this.account))return uni.showToast({title:'请输入正确手机号',icon:'none'});try{const res=await authApi.sendCode(this.account);if(res?.debug_code)this.smsCode=res.debug_code;this.countdown=60;this.timer=setInterval(()=>{this.countdown--;if(!this.countdown)clearInterval(this.timer)},1000);uni.showToast({title:'验证码已发送',icon:'none'})}catch(e){uni.showToast({title:e.message,icon:'none'})}},async submit(){if(!this.agreed)return uni.showToast({title:'请先同意用户协议与隐私政策',icon:'none'});if(!this.account||!this.credential)return uni.showToast({title:'请填写手机号和密码',icon:'none'});this.submitting=true;try{if(this.mode==='register'){if(this.credential.length<8)return uni.showToast({title:'密码至少 8 位',icon:'none'});if(!/^\d{6}$/.test(this.smsCode))return uni.showToast({title:'请输入 6 位验证码',icon:'none'});await authApi.register({phone:this.account,password:this.credential,sms_code:this.smsCode,nickname:this.nickname||undefined});this.mode='password';this.smsCode='';uni.showToast({title:'注册成功，请登录',icon:'none'});return}const res=await authApi.login({account:this.account,password:this.credential});setTokens(res);uni.showToast({title:'登录成功'});setTimeout(()=>uni.reLaunch({url:'/pages/home/index'}),500)}catch(e){uni.showToast({title:e.message,icon:'none'})}finally{this.submitting=false}},guest(){uni.reLaunch({url:'/pages/home/index'})}}}
</script>
<style scoped lang="scss">
.login-page{display:grid;min-height:100vh;grid-template-columns:minmax(0,1.65fr) minmax(420px,.85fr);background:#fffaf5}.login-visual{position:relative;display:flex;overflow:hidden;flex-direction:column;padding:44px 7%;background:radial-gradient(circle at 65% 70%,#fff 0,#ffe8ce 24%,transparent 25%),linear-gradient(120deg,#fff8ed,#ffd9af)}.brand,.mobile-brand{color:var(--color-primary);font-size:25px;font-weight:900}.visual-copy{position:relative;z-index:2;margin-top:17vh}.visual-title,.visual-sub{display:block;color:#71452b}.visual-title{font-size:43px;font-weight:800}.visual-sub{margin-top:18px;font-size:19px;letter-spacing:5px}.trust{display:flex;gap:28px;margin-top:28px;color:#8a624b;font-size:14px}.animals{position:absolute;right:4%;bottom:8%;font-size:150px;letter-spacing:-45px;filter:drop-shadow(0 20px 18px rgba(90,48,20,.12))}.login-panel{display:flex;flex-direction:column;justify-content:center;padding:12%;background:#fff}.mobile-brand{display:none;text-align:center}.tabs{display:grid;grid-template-columns:1fr 1fr;margin-bottom:28px;border-bottom:1px solid var(--color-border)}.tabs view{position:relative;padding:16px;text-align:center;color:var(--color-text-secondary);font-size:15px}.tabs .active{color:var(--color-primary);font-weight:700}.tabs .active::after{position:absolute;right:20px;bottom:-1px;left:20px;height:2px;background:var(--color-primary);content:""}.field{display:flex;height:52px;align-items:center;gap:12px;margin-bottom:15px;padding:0 17px;border:1px solid var(--color-border);border-radius:14px;color:#888}.field input{flex:1;font-size:14px}.code-button{color:var(--color-primary);font-size:12px;white-space:nowrap}.agreement{display:flex;align-items:center;gap:8px;margin:4px 0 20px;color:var(--color-text-secondary);font-size:11px}.check{display:flex;width:18px;height:18px;align-items:center;justify-content:center;border:1px solid #ccc;border-radius:50%}.check.checked{border-color:var(--color-primary);background:var(--color-primary);color:#fff}.login-extra{display:flex;justify-content:space-between;margin-top:18px;color:var(--color-primary);font-size:12px}.security-tip{margin-top:34px;padding-top:18px;border-top:1px solid var(--color-border);color:#aaa;font-size:10px;line-height:1.6;text-align:center}
@media(max-width:767px){.login-page{display:flex;min-height:100vh;flex-direction:column;background:linear-gradient(#fff2df 0,#fffaf5 46%,#fff 46%)}.login-visual{min-height:300px;padding:28px 24px;background:transparent}.brand{display:none}.visual-copy{margin-top:34px;text-align:center}.visual-title{font-size:31px}.visual-sub{margin-top:9px;font-size:13px;letter-spacing:3px}.trust{justify-content:center;gap:16px;margin-top:16px;font-size:10px}.animals{right:50%;bottom:-12px;font-size:94px;transform:translateX(45%)}.login-panel{position:relative;z-index:2;flex:1;margin-top:-12px;padding:24px 24px 40px;border-radius:28px 28px 0 0;box-shadow:0 -8px 30px rgba(87,53,27,.06)}.mobile-brand{display:block;margin-bottom:10px;font-size:21px}.tabs{margin-bottom:20px}.field{height:50px}.security-tip{margin-top:24px}}
</style>
