<template>
	<view class="admin-shell">
		<view class="admin-bar"><view><text class="brand">PetMall Admin</text><text class="sub">审核与平台治理中心</text></view><view class="admin-actions"><text>{{admin.nickname||admin.phone}}</text><button class="secondary-button" @click="logout">退出</button></view></view>
		<view class="admin-layout">
			<view class="sidebar"><view v-for="item in tabs" :key="item.key" :class="{active:tab===item.key}" @click="tab=item.key"><text>{{item.icon}}</text>{{item.label}}</view><view @click="home">← 返回用户端</view></view>
			<scroll-view scroll-y class="workspace"><view class="workspace-inner">
				<view class="page-heading"><view><text class="page-title">{{activeTab.label}}</text><text class="page-subtitle">{{activeTab.desc}}</text></view><button class="secondary-button" :loading="loading" @click="loadAll">刷新数据</button></view>
				<view v-if="loading" class="card empty-inline">正在加载后台数据…</view>

				<template v-else-if="tab==='dashboard'">
					<view class="metric-grid"><view v-for="m in metrics" :key="m.label" class="card metric"><text>{{m.value}}</text><text>{{m.label}}</text></view></view>
					<view class="content-grid overview"><view class="card panel"><text class="panel-title">待办提醒</text><view class="data-list"><view class="data-row"><text class="data-main">待审核商品</text><text class="status-chip">{{products.length}}</text></view><view class="data-row"><text class="data-main">待审核商家</text><text class="status-chip">{{merchants.length}}</text></view><view class="data-row"><text class="data-main">领养申请</text><text class="status-chip">{{adoptions.length}}</text></view><view class="data-row"><text class="data-main">内容举报</text><text class="status-chip">{{reports.length}}</text></view></view></view>
					<view class="card panel"><text class="panel-title">统计口径说明</text><text class="data-meta">当前统计来自后台已有列表接口，用于展示可管理数据，不代表完整经营报表。后端尚未提供 GMV、订单趋势、宠物总量等聚合统计接口。</text></view></view>
				</template>

				<view v-else-if="tab==='users'" class="card panel"><text class="panel-title">平台用户</text><StatePanel v-if="!users.length" icon="♙" title="暂无用户数据"/><view v-else class="data-list"><view v-for="item in users" :key="item.id" class="data-row"><view class="data-main"><text class="data-title">{{item.nickname||item.phone}}</text><text class="data-meta">{{item.phone}} · {{item.is_admin?'管理员':'普通用户'}} · {{item.is_merchant?'商家':'非商家'}}</text></view><text class="status-chip">{{item.is_frozen?'已冻结':'正常'}}</text><button v-if="item.is_frozen" class="secondary-button" @click="unfreeze(item)">解冻</button><button v-else class="danger-button" @click="freeze(item)">冻结</button></view></view></view>

				<view v-else-if="tab==='products'" class="card panel"><text class="panel-title">待审核商品</text><StatePanel v-if="!products.length" icon="▣" title="没有待审核商品"/><view v-else class="data-list"><view v-for="item in products" :key="item.id" class="data-row"><view class="data-main"><text class="data-title">{{item.title}}</text><text class="data-meta">商家 {{item.merchant_id}} · 库存 {{item.stock}} · SKU {{item.skus?.length||0}}</text></view><button class="action-button" @click="approveProduct(item)">通过</button><button class="danger-button" @click="rejectProduct(item)">驳回</button></view></view></view>

				<view v-else-if="tab==='merchants'" class="card panel"><text class="panel-title">待审核商家</text><StatePanel v-if="!merchants.length" icon="▦" title="没有待审核商家"/><view v-else class="data-list"><view v-for="item in merchants" :key="item.id" class="data-row"><view class="data-main"><text class="data-title">{{item.shop_name}}</text><text class="data-meta">{{item.contact_name}} · {{item.contact_phone}} · {{item.business_scope}}</text></view><button class="action-button" @click="approveMerchant(item)">通过</button><button class="danger-button" @click="rejectMerchant(item)">驳回</button></view></view></view>

				<view v-else-if="tab==='content'" class="card panel"><text class="panel-title">内容举报</text><StatePanel v-if="!reports.length" icon="◉" title="没有待处理举报"/><view v-else class="data-list"><view v-for="item in reports" :key="item.id" class="data-row"><view class="data-main"><text class="data-title">{{item.target_type}} #{{item.target_id}}</text><text class="data-meta">举报人 {{item.reporter_id}} · {{item.reason}} · {{item.status}}</text></view><button class="secondary-button" @click="resolveReport(item,'dismiss')">驳回举报</button><button class="danger-button" @click="resolveReport(item,'take_down')">下架内容</button></view></view></view>

				<view v-else-if="tab==='adoptions'" class="card panel"><text class="panel-title">领养申请审核</text><StatePanel v-if="!adoptions.length" icon="♡" title="没有待审核领养申请"/><view v-else class="data-list"><view v-for="item in adoptions" :key="item.id" class="data-row"><view class="data-main"><text class="data-title">{{item.contact_name}} · {{item.contact_phone}}</text><text class="data-meta">{{item.living_city}} · {{item.living_condition}} · {{item.reason}}</text></view><text class="status-chip">{{item.status}}</text><button v-if="item.status==='pending'" class="action-button" @click="approveAdoption(item)">通过</button><button v-if="item.status==='pending'" class="danger-button" @click="rejectAdoption(item)">驳回</button></view></view></view>

				<view v-else-if="tab==='pets'" class="card panel"><StatePanel icon="🐾" title="管理员宠物管理接口未开放" description="现有 /pets 接口仅允许用户查看自己的宠物，后台无法安全获取全平台宠物列表。页面入口已保留，待后端提供管理员专用接口。"/></view>
				<view v-else-if="tab==='orders'" class="card panel"><StatePanel icon="▣" title="管理员订单管理接口未开放" description="现有 /orders 接口仅返回当前用户订单，后台无法查看全平台订单。页面入口已保留，不能使用普通用户接口越权替代。"/></view>
			</view></scroll-view>
		</view>
	</view>
</template>
<script>
import StatePanel from '../../components/StatePanel.vue';import{adminApi,userApi,clearTokens}from'../../api'
export default{components:{StatePanel},data(){return{tab:'dashboard',loading:true,admin:{},users:[],products:[],merchants:[],reports:[],adoptions:[],tabs:[{key:'dashboard',icon:'▤',label:'数据面板',desc:'平台待办和已有数据概览'},{key:'users',icon:'♙',label:'用户管理',desc:'账号状态与冻结管理'},{key:'products',icon:'▣',label:'商品管理',desc:'审核商家提交的商品'},{key:'pets',icon:'🐾',label:'宠物管理',desc:'管理员宠物接口状态'},{key:'orders',icon:'▦',label:'订单管理',desc:'管理员订单接口状态'},{key:'merchants',icon:'店',label:'商家审核',desc:'审核商家入驻申请'},{key:'content',icon:'◉',label:'内容审核',desc:'处理社区内容举报'},{key:'adoptions',icon:'♡',label:'领养审核',desc:'审核用户领养申请'}]}},computed:{activeTab(){return this.tabs.find(v=>v.key===this.tab)||this.tabs[0]},metrics(){return[{label:'平台用户',value:this.users.length},{label:'待审商品',value:this.products.length},{label:'待审商家',value:this.merchants.length},{label:'内容举报',value:this.reports.length},{label:'领养申请',value:this.adoptions.length}]}},onLoad(){this.loadAll()},methods:{
	async loadAll(){this.loading=true;try{this.admin=await userApi.me();if(!this.admin.is_admin){clearTokens();return uni.reLaunch({url:'/pages/admin/login'})}}catch(e){return uni.reLaunch({url:'/pages/admin/login'})}const r=await Promise.allSettled([adminApi.users(),adminApi.pendingProducts({page:1,page_size:100}),adminApi.pendingMerchants(),adminApi.reports({page:1,page_size:100}),adminApi.adoptionApplications({})]);if(r[0].status==='fulfilled')this.users=r[0].value||[];if(r[1].status==='fulfilled')this.products=r[1].value?.items||[];if(r[2].status==='fulfilled')this.merchants=r[2].value||[];if(r[3].status==='fulfilled')this.reports=r[3].value?.items||[];if(r[4].status==='fulfilled')this.adoptions=r[4].value||[];this.loading=false},
	reason(title,callback,required=false){uni.showModal({title,editable:true,placeholderText:required?'请输入原因（必填）':'审核备注（可选）',success:r=>{if(r.confirm&&(!required||r.content))callback(r.content||null);else if(r.confirm)uni.showToast({title:'请输入原因',icon:'none'})}})},
	freeze(item){this.reason('冻结用户',async reason=>{try{await adminApi.freezeUser(item.id,{reason});uni.showToast({title:'用户已冻结'});this.loadAll()}catch(e){}},true)},unfreeze(item){this.reason('解冻用户',async reason=>{try{await adminApi.unfreezeUser(item.id,{reason});uni.showToast({title:'用户已解冻'});this.loadAll()}catch(e){}})},
	approveProduct(item){this.reason('通过商品审核',async reason=>{try{await adminApi.approveProduct(item.id,{reason});uni.showToast({title:'商品已通过'});this.loadAll()}catch(e){}})},rejectProduct(item){this.reason('驳回商品',async reason=>{try{await adminApi.rejectProduct(item.id,{reason});uni.showToast({title:'商品已驳回'});this.loadAll()}catch(e){}},true)},
	approveMerchant(item){this.reason('通过商家审核',async reason=>{try{await adminApi.approveMerchant(item.id,{reason});uni.showToast({title:'商家已通过'});this.loadAll()}catch(e){}})},rejectMerchant(item){this.reason('驳回商家',async reason=>{try{await adminApi.rejectMerchant(item.id,{reason});uni.showToast({title:'商家已驳回'});this.loadAll()}catch(e){}},true)},
	resolveReport(item,action){this.reason(action==='take_down'?'下架被举报内容':'驳回举报',async reason=>{try{await adminApi.resolveReport(item.id,{action,reason});uni.showToast({title:'举报已处理'});this.loadAll()}catch(e){}})},
	approveAdoption(item){this.reason('通过领养申请',async reason=>{try{await adminApi.approveAdoptionApplication(item.id,{reason});uni.showToast({title:'申请已通过'});this.loadAll()}catch(e){}})},rejectAdoption(item){this.reason('驳回领养申请',async reason=>{try{await adminApi.rejectAdoptionApplication(item.id,{reason});uni.showToast({title:'申请已驳回'});this.loadAll()}catch(e){}},true)},
	logout(){clearTokens();uni.reLaunch({url:'/pages/admin/login'})},home(){uni.reLaunch({url:'/pages/home/index'})}
}}
</script>
<style scoped lang="scss">
.admin-shell{height:100vh;background:#f7f7f8}.admin-bar{display:flex;height:68px;align-items:center;justify-content:space-between;padding:0 25px;border-bottom:1px solid #e7e7e9;background:#fff}.brand,.sub{display:block}.brand{font-size:20px;font-weight:800}.sub{margin-top:3px;color:#888;font-size:10px}.admin-actions{display:flex;align-items:center;gap:12px;font-size:12px}.admin-layout{display:grid;height:calc(100vh - 68px);grid-template-columns:210px 1fr}.sidebar{padding:16px 10px;background:#24262c;color:#bbb}.sidebar view{display:flex;align-items:center;gap:10px;margin:3px 0;padding:12px 14px;border-radius:9px;font-size:12px}.sidebar view.active{background:var(--color-primary);color:#fff}.workspace{height:100%}.workspace-inner{padding:24px}.metric-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.metric{display:flex;flex-direction:column;gap:8px;padding:20px}.metric text:first-child{font-size:27px;font-weight:800}.metric text:last-child{color:var(--color-text-secondary);font-size:11px}.overview{margin-top:16px}@media(max-width:767px){.admin-bar{height:58px;padding:0 12px}.admin-layout{height:calc(100vh - 58px);grid-template-columns:64px 1fr}.sidebar{padding:8px 5px}.sidebar view{justify-content:center;padding:11px 5px;font-size:0}.sidebar view text{font-size:18px}.workspace-inner{padding:12px}.metric-grid{grid-template-columns:repeat(2,1fr)}}
</style>
