<template>
	<AppShell active="community"><view class="page-container">
		<view v-if="loading" class="card empty-inline">正在加载动态…</view>
		<StatePanel v-else-if="!post" icon="⚠" title="动态不存在" action="返回社区" @action="back"/>
		<template v-else><view class="content-grid">
			<view class="card panel"><view class="author"><text class="avatar">🐾</text><view><text class="data-title">宠友 {{post.user_id}}</text><text class="data-meta">{{post.created_at}}</text></view><button class="secondary-button" @click="follow">关注</button></view><text class="content">{{post.content||'分享了一组宠物照片'}}</text><view class="media"><image v-for="m in post.media" :key="m.id" :src="m.file_url" mode="aspectFill"/></view><view class="button-row"><button class="secondary-button" @click="like">♡ {{post.like_count}}</button><button class="secondary-button" @click="favorite">收藏 {{post.favorite_count}}</button><button class="danger-button" @click="report">举报</button></view></view>
			<view class="card panel"><text class="panel-title">评论 {{post.comment_count}}</text><view v-if="!comments.length" class="empty-inline">还没有评论，来聊两句吧</view><view v-else class="data-list"><view v-for="item in comments" :key="item.id" class="data-row"><view class="data-main"><text class="data-title">用户 {{item.user_id}}</text><text class="data-meta">{{item.content}}</text></view><button class="danger-button" @click="deleteComment(item.id)">删除</button></view></view><view class="form-field"><textarea v-model="comment" placeholder="友善交流，分享真实经验"/></view><view class="button-row"><button class="action-button" @click="sendComment">发表评论</button></view></view>
		</view></template>
	</view></AppShell>
</template>
<script>
import AppShell from '../../components/AppShell.vue';import StatePanel from '../../components/StatePanel.vue';import{communityApi}from'../../api'
export default{components:{AppShell,StatePanel},data(){return{id:null,post:null,comments:[],comment:'',loading:true}},onLoad(q){this.id=q.id;this.load()},methods:{async load(){this.loading=true;const r=await Promise.allSettled([communityApi.detail(this.id),communityApi.comments(this.id)]);this.post=r[0].status==='fulfilled'?r[0].value:null;this.comments=r[1].status==='fulfilled'?r[1].value:[];this.loading=false},async like(){try{await communityApi.like(this.id);uni.showToast({title:'已点赞'});this.load()}catch(e){}},async favorite(){try{await communityApi.favorite(this.id);uni.showToast({title:'已收藏'});this.load()}catch(e){}},async follow(){try{await communityApi.follow(this.post.user_id);uni.showToast({title:'已关注'})}catch(e){}},async sendComment(){if(!this.comment.trim())return;try{await communityApi.createComment(this.id,{content:this.comment});this.comment='';uni.showToast({title:'评论已发布'});this.load()}catch(e){}},async deleteComment(id){try{await communityApi.deleteComment(this.id,id);uni.showToast({title:'评论已删除'});this.load()}catch(e){}},report(){uni.showModal({title:'举报动态',editable:true,placeholderText:'请输入举报原因',success:async r=>{if(r.confirm&&r.content)try{await communityApi.report(this.id,{target_type:'post',target_id:Number(this.id),reason:r.content});uni.showToast({title:'举报已提交'})}catch(e){}}})},back(){uni.navigateBack()}}}
</script>
<style scoped>.author{display:flex;align-items:center;gap:12px}.author button{margin-left:auto}.avatar{display:flex;width:44px;height:44px;align-items:center;justify-content:center;border-radius:50%;background:var(--color-primary-soft)}.content{display:block;margin:24px 0;font-size:16px;line-height:1.9}.media{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.media image{width:100%;height:190px;border-radius:10px}@media(max-width:767px){.media image{height:110px}}</style>
