<template>
	<AppShell active="adoption"><view class="page-container">
		<view class="adoption-hero"><view><text class="hero-tag">温暖领养计划</text><text class="hero-title">遇见它，也遇见一生的陪伴</text><text class="hero-sub">领养不是选择一只宠物，而是迎接一位家人</text><view class="hero-actions"><button @click="publish">发布领养</button><button @click="my">我的申请</button></view></view><text class="hero-pets">🐕　🐈</text></view>
		<view class="filter-row"><view v-for="item in filters" :key="item" class="filter" :class="{active:activeFilter===item}" @click="activeFilter=item">{{item}}</view></view>
		<StatePanel v-if="loading" icon="…" title="正在加载领养信息"/>
		<StatePanel v-else-if="error" icon="⚠" title="领养信息加载失败" :description="error" action="重试" @action="load"/>
		<StatePanel v-else-if="!displayPets.length" icon="♡" title="暂无待领养宠物" description="你也可以发布需要寻找新家的宠物" action="发布领养" @action="publish"/>
		<view v-else class="adoption-grid">
			<view v-for="(pet,index) in displayPets" :key="pet.id||index" class="adoption-card card" @click="detail(pet.id)">
				<image v-if="pet.cover_image" class="pet-image" :src="assetUrl(pet.cover_image)" mode="aspectFill"/><view v-else class="pet-image pet-placeholder">{{pet.species==='猫'?'🐱':'🐶'}}</view>
				<view class="pet-body"><view class="pet-title-row"><text class="pet-name">{{pet.name}}</text><text class="pet-status">{{pet.status==='available'?'待领养':'了解更多'}}</text></view><text class="pet-meta">{{pet.age_text||'年龄待补充'}} · {{pet.gender||'性别待补充'}} · {{pet.breed||pet.species}}</text><text class="pet-location">⌖ {{pet.city}}</text><text class="pet-description">{{pet.description}}</text></view>
			</view>
		</view>
	</view></AppShell>
</template>
<script>
import AppShell from '../../components/AppShell.vue';import StatePanel from '../../components/StatePanel.vue';import{adoptionApi,assetUrl}from'../../api'
export default{components:{AppShell,StatePanel},data(){return{items:[],error:'',loading:true,activeFilter:'全部',filters:['全部','狗狗','猫咪','小宠']}},computed:{displayPets(){if(this.activeFilter==='狗狗')return this.items.filter(v=>v.species.includes('狗'));if(this.activeFilter==='猫咪')return this.items.filter(v=>v.species.includes('猫'));return this.items}},onLoad(){this.load()},methods:{assetUrl,async load(){this.loading=true;this.error='';try{this.items=await adoptionApi.list()||[]}catch(e){this.error=e.message}finally{this.loading=false}},detail(id){uni.navigateTo({url:`/pages/adoption/detail?id=${id}`})},publish(){uni.navigateTo({url:uni.getStorageSync('access_token')?'/pages/adoption/publish':'/pages/auth/login'})},my(){uni.navigateTo({url:uni.getStorageSync('access_token')?'/pages/adoption/my':'/pages/auth/login'})}}}
</script>
<style scoped lang="scss">
.adoption-hero{display:flex;min-height:240px;align-items:center;justify-content:space-between;padding:42px 7%;overflow:hidden;border-radius:24px;background:linear-gradient(115deg,#fff1df,#ffe0c4);color:#623a22}.hero-tag,.hero-title,.hero-sub{display:block}.hero-tag{color:var(--color-primary);font-size:13px;font-weight:800;letter-spacing:2px}.hero-title{margin:16px 0 12px;font-size:34px;font-weight:800}.hero-sub{color:#89644c;font-size:15px}.hero-pets{font-size:94px;filter:drop-shadow(0 10px 12px rgba(82,47,18,.1))}.filter-row{display:flex;gap:10px;margin:22px 0}.filter{padding:9px 22px;border-radius:20px;background:#fff;color:#7e756e;font-size:13px}.filter.active{background:var(--color-primary);color:#fff}.adoption-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.adoption-card{overflow:hidden}.pet-image{display:block;width:100%;height:240px;overflow:hidden;background:#f5eae0;object-fit:cover}.pet-placeholder{display:flex;align-items:center;justify-content:center;font-size:85px}.pet-body{padding:16px}.pet-title-row{display:flex;align-items:center;justify-content:space-between}.pet-name{font-size:18px;font-weight:800}.pet-status{padding:4px 9px;border-radius:10px;background:var(--color-primary-soft);color:var(--color-primary);font-size:10px}.pet-meta,.pet-location,.pet-description{display:block}.pet-meta,.pet-location{margin-top:8px;color:var(--color-text-secondary);font-size:12px}.pet-description{display:-webkit-box;overflow:hidden;margin-top:12px;font-size:13px;line-height:1.6;-webkit-box-orient:vertical;-webkit-line-clamp:2}
.hero-actions{display:flex;gap:8px;margin-top:18px}.hero-actions button{height:34px;margin:0;padding:0 15px;border-radius:18px;background:#fff;color:var(--color-primary);font-size:11px;line-height:34px}
@media(max-width:1100px){.adoption-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.adoption-hero{min-height:170px;padding:24px 20px}.hero-title{font-size:22px}.hero-sub{font-size:11px}.hero-pets{font-size:50px}.adoption-grid{grid-template-columns:1fr;gap:12px}.adoption-card{display:grid;grid-template-columns:125px 1fr}.pet-image{height:100%;min-height:165px}.pet-placeholder{font-size:55px}.pet-body{padding:13px}.filter-row{overflow:auto;margin:14px 0}.filter{flex:none}}
</style>
