<template>
	<AppShell active="mall" :cart-count="items.length"><view class="page-container">
		<view class="page-head"><text class="title">购物车（{{items.length}}）</text><text class="manage">管理</text></view>
		<StatePanel v-if="!loggedIn" icon="🛒" title="登录后查看购物车" description="已选好物会安全保存在你的账号中" action="去登录" @action="goLogin"/>
		<StatePanel v-else-if="error" icon="⚠" title="购物车加载失败" :description="error" action="重试" @action="load"/>
		<StatePanel v-else-if="!items.length" icon="🛒" title="购物车还是空的" description="去商城挑选适合毛孩子的好物吧" action="去逛逛" @action="goMall"/>
		<view v-else class="cart-layout"><view class="cart-list card"><view v-for="item in items" :key="item.id" class="cart-item"><text class="select" :class="{active:item.selected}" @click="toggle(item)">{{item.selected?'✓':''}}</text><image v-if="item.product.cover_image" class="item-image" :src="assetUrl(item.product.cover_image)" mode="aspectFill"/><view v-else class="item-image placeholder">🥫</view><view class="item-copy"><text class="item-title">{{item.product.title}}</text><text class="sku">{{item.sku.name}}</text><text class="price">{{money(item.sku.price)}}</text></view><view class="quantity"><button @click="update(item,-1)">−</button><text>{{item.quantity}}</text><button @click="update(item,1)">＋</button></view><button class="remove" @click="remove(item)">×</button></view></view><view class="summary card"><text class="summary-title">订单结算</text><view><text>已选商品</text><text>{{selectedItems.length}} 件</text></view><view><text>商品合计</text><text>{{money(total)}}</text></view><view class="total"><text>合计</text><text>{{money(total)}}</text></view><button class="primary-button" @click="checkout">去结算</button><text class="tip">结算页仅提交后端支持的地址与购物车商品，不伪造优惠券和宠物币抵扣。</text></view></view>
	</view></AppShell>
</template>
<script>
import AppShell from '../../components/AppShell.vue';import StatePanel from '../../components/StatePanel.vue';import{assetUrl,cartApi}from'../../api';import{formatMoney}from'../../utils/format'
export default{components:{AppShell,StatePanel},data(){return{items:[],error:''}},computed:{loggedIn(){return!!uni.getStorageSync('access_token')},selectedItems(){return this.items.filter(v=>v.selected&&v.available)},total(){return this.selectedItems.reduce((sum,v)=>sum+Number(v.subtotal||v.sku.price*v.quantity),0)}},onShow(){if(this.loggedIn)this.load()},methods:{assetUrl,money:formatMoney,goLogin(){uni.navigateTo({url:'/pages/auth/login'})},goMall(){uni.reLaunch({url:'/pages/mall/index'})},async load(){this.error='';try{this.items=await cartApi.list()||[]}catch(e){this.error=e.message}},async toggle(item){const before=item.selected;item.selected=!before;try{await cartApi.update(item.id,{selected:item.selected})}catch(e){item.selected=before}},async update(item,delta){const next=Math.max(1,Math.min(99,item.quantity+delta));if(next===item.quantity)return;const before=item.quantity;item.quantity=next;try{const fresh=await cartApi.update(item.id,{quantity:next});Object.assign(item,fresh)}catch(e){item.quantity=before}},async remove(item){try{await cartApi.remove(item.id);uni.showToast({title:'商品已移除'});this.load()}catch(e){}},checkout(){if(!this.selectedItems.length)return uni.showToast({title:'请先选择商品',icon:'none'});uni.navigateTo({url:`/pages/order/confirm?items=${this.selectedItems.map(v=>v.id).join(',')}`})}}}
</script>
<style scoped lang="scss">
.page-head{display:flex;align-items:center;justify-content:space-between;margin:12px 0 24px}.title{font-size:28px;font-weight:800}.manage{color:var(--color-primary);font-size:13px}.cart-layout{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:20px;align-items:start}.cart-list{padding:8px 22px}.cart-item{display:flex;align-items:center;gap:16px;padding:18px 0}.cart-item+.cart-item{border-top:1px solid var(--color-border)}.select{display:flex;width:21px;height:21px;align-items:center;justify-content:center;border:1px solid #ccc;border-radius:50%;font-size:11px}.select.active{border-color:var(--color-primary);background:var(--color-primary);color:#fff}.item-image{width:90px;height:90px;border-radius:12px;background:#f5ede5}.placeholder{display:flex;align-items:center;justify-content:center;font-size:42px}.item-copy{display:flex;flex:1;min-width:0;flex-direction:column}.item-title{overflow:hidden;font-size:14px;font-weight:700;text-overflow:ellipsis;white-space:nowrap}.sku{margin-top:7px;color:var(--color-text-secondary);font-size:11px}.price{margin-top:12px;color:var(--color-primary);font-size:16px;font-weight:800}.quantity{display:flex;align-items:center;border:1px solid var(--color-border);border-radius:17px}.quantity button{width:30px;height:30px;margin:0;padding:0;background:#fff;font-size:13px;line-height:30px}.quantity text{width:28px;text-align:center;font-size:12px}.remove{width:28px;height:28px;margin:0;padding:0;border-radius:50%;background:#fff0f0;color:var(--color-danger);line-height:28px}.summary{position:sticky;top:90px;padding:24px}.summary-title{display:block;margin-bottom:20px;font-size:19px;font-weight:800}.summary>view{display:flex;justify-content:space-between;margin:12px 0;color:var(--color-text-secondary);font-size:13px}.summary .total{margin-top:20px;padding-top:18px;border-top:1px solid var(--color-border);color:var(--color-text);font-weight:700}.summary .total text:last-child{color:var(--color-primary);font-size:21px}.summary .primary-button{margin-top:20px}.tip{display:block;margin-top:15px;color:#aaa;font-size:10px;line-height:1.6}
@media(max-width:900px){.page-head{margin:5px 0 15px}.title{font-size:22px}.cart-layout{display:block}.cart-list{padding:0 14px}.cart-item{gap:9px;padding:14px 0}.item-image{width:70px;height:70px}.quantity button{width:25px}.quantity text{width:22px}.summary{position:static;margin-top:12px;padding:18px}}
</style>
